name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # JOB 1: INTEGRAÇÃO CONTÍNUA (Rodar Testes)
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # Ajuste conforme a versão do seu go.mod

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        # Como você tem o arquivo handlers_test.go, isso vai testar sua API
        run: go test -v ./...

  # JOB 2: ENTREGA CONTÍNUA (Deploy)
  # Este job só roda se o job 'tests' passar (needs: tests)
  deploy_app:
    name: Deploy Application
    needs: tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      # 1. Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 2. Construir e Enviar para o Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Lembre-se de atualizar o docker-compose.yml com essa mesma tag!
          tags: elvinhokj/locadora-api:latest

      # 3. Copiar APENAS o docker-compose.yml para o servidor
      - name: Copy docker-compose to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/root/locadora-api"

      # 4. Conectar no Servidor e Atualizar
      - name: Execute Remote Deploy
        uses: appleboy/ssh-action@v1.0.0
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: "db"
          DB_PORT: "5432"
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DB_USER,DB_PASSWORD,DB_NAME,DB_HOST,DB_PORT
          script: |
            cd /root/locadora-api
            
            # Recria o arquivo .env com as variáveis seguras
            echo "DB_USER=$DB_USER" > .env
            echo "DB_PASSWORD=$DB_PASSWORD" >> .env
            echo "DB_NAME=$DB_NAME" >> .env
            echo "DB_HOST=$DB_HOST" >> .env
            echo "DB_PORT=$DB_PORT" >> .env
            
            # Baixa a versão nova e reinicia
            docker-compose pull
            docker-compose up -d --remove-orphans
            docker image prune -f